services:
  postgres:
    image: postgres:18
    container_name: around-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: around
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./feature/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./feature/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
      - ./feature/database/users.sql:/docker-entrypoint-initdb.d/03-users.sql:ro

  redis:
    image: redis:7-alpine
    container_name: around-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
